### ISSUE TITLE
not sure what im doing wrong, followed the quickstart to a T

### ISSUE THREAD

**Issue by JustGanon** [jbh-cloud/spotify_sync#25]
after configuring i got this following error

`Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Program Files\Python311\Scripts\spotify_sync.exe\__main__.py", line 7, in <module>
  File "C:\Program Files\Python311\Lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\spotify_sync\__main__.py", line 48, in auto
    app.auto()
  File "C:\Program Files\Python311\Lib\site-packages\spotify_sync\cli.py", line 43, in auto
    self._setup()
  File "C:\Program Files\Python311\Lib\site-packages\spotify_sync\cli.py", line 318, in _setup
    self._load_config()
  File "C:\Program Files\Python311\Lib\site-packages\spotify_sync\cli.py", line 308, in _load_config
    self.config = load_config()
                  ^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\spotify_sync\config.py", line 407, in load
    data=ConfigLoader(profile=profile).load(),
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\spotify_sync\config.py", line 223, in __init__
    self._load_config()
  File "C:\Program Files\Python311\Lib\site-packages\spotify_sync\config.py", line 302, in _load_config
    self._config = json.load(f)
                   ^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: Invalid \escape: line 6 column 29 (char 309)`

**Comment by jbh-cloud** [comment]
Looks to be a json parsing issue, try pasting the contents of your
config.json into a json validator such as jsonlint.com

**Comment by jbh-cloud** [comment]
Closing this as assumed fixed
