### ISSUE TITLE
Can't add my config to the profile cache

### ISSUE THREAD

**Issue by Tiliii** [jbh-cloud/spotify_sync#26]
I don't really know what ham doing wrong here, so any help is appreciated 

That's what terminal is printing out whenever I try to add the config to the profile cache:

til@wl-pool2-pnt-24480 ~ % spotify_sync config add myFirstProfile ./config.json
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/bin/spotify_sync", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/spotify_sync/__main__.py", line 226, in config_add
    app.cache_config_profile(name, path)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/spotify_sync/cli.py", line 177, in cache_config_profile
    self.cc.add(name, path)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/spotify_sync/config.py", line 64, in add
    c_loader = ConfigLoader(config_file=Path(path))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/spotify_sync/config.py", line 223, in __init__
    self._load_config()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/spotify_sync/config.py", line 302, in _load_config
    self._config = json.load(f)
                   ^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 23 column 26 (char 950)
til@wl-pool2-pnt-24480 ~ %

**Comment by Tiliii** [comment]
it was my mistake sorry, I did mess up the config...
