### ISSUE TITLE
Can't even open the script after installing it

### ISSUE THREAD

**Issue by Tiliii** [jbh-cloud/spotify_sync#34]
that's what the terminal is throwing at me after I installed it.

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/bin/spotify_sync", line 5, in <module>
    from spotify_sync.__main__ import cli
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/spotify_sync/__main__.py", line 5, in <module>
    from spotify_sync.cli import SpotifySyncApp
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/spotify_sync/cli.py", line 7, in <module>
    from spotify_sync.stats import (
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/spotify_sync/stats.py", line 5, in <module>
    from spotify_sync.spotify_ import SpotifyService
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/spotify_sync/spotify_.py", line 8, in <module>
    from spotify_sync.config import Config
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/spotify_sync/config.py", line 13, in <module>
    from pkg_resources import resource_stream
ModuleNotFoundError: No module named 'pkg_resources'

I have absolutely no idea why or how I can resolve this. I tried reinstalling, restarting my Mac, restarting terminal and so on.

**Comment by Tiliii** [comment]
Had to download pip setuptools.
